name: Regenerate course overview

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Liaex
        run: echo "Running liaex!"
